options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build and deploy container image directly to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sauce-app'
      - '--source'
      - './app'
      - '--region'
      - 'us-central1'
      - '--port'
      - '5001'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},SUPABASE_JWT_SECRET=${_SUPABASE_JWT_SECRET},SUPABASE_PROJECT_ID=${_SUPABASE_PROJECT_ID},SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY},SUPABASE_URL=${_SUPABASE_URL},VAPID_PUBLIC_KEY=${_VAPID_PUBLIC_KEY},VAPID_PRIVATE_KEY=${_VAPID_PRIVATE_KEY}'
